inherit_from: ../hitobito/.rubocop.yml

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - db/**/*
    - lib/**/*.rake
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - spec/**/*
    - test/**/*
