#  Copyright (c) 2017, hitobito AG. This file is part of
#  hitobito_tenants and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_tenants.


# Settings relevant for the hitobito_tenants wagon
# Overrides settings from the main application
application:

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito@puzzle.ch

tenants:
  domain: <%= ENV['RAILS_HOST_NAME'] || 'hitobito.local' %>
  subdomains:
    admin: <%= ENV['RAILS_ADMIN_SUBDOMAIN'] || 'admin' %>
    excluded:
      <% ENV['RAILS_EXCLUDED_SUBDOMAINS'].to_s.split(',').each do |d| %>
      - <%= d.strip %>
      <% end %>
